package ArduinoML.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;

@Generated
public class QueriesGenerated {
  public static Object propertyMacro_GetPropertyValue_1933305387245017213(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e6606536afe7L, 0x76e4e660653879ccL, "init_state")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetPropertyValue_8567225692854941212(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e6606536afe0L, 0x76e4e6606536afe3L, "pin"));
  }
  public static Object propertyMacro_GetPropertyValue_8567225692854946391(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e6606536afe0L, 0x76e4e6606536afe3L, "pin"));
  }
  public static Object propertyMacro_GetPropertyValue_1933305387245039686(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e66065386d6bL, 0x76e4e660653879a5L, "actuator")), MetaAdapterFactory.getProperty(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e6606536afe0L, 0x76e4e6606536afe3L, "pin"));
  }
  public static Object propertyMacro_GetPropertyValue_5586951442585352482(final PropertyMacroContext _context) {
    return (SPropertyOperations.getBoolean_def(_context.getNode(), MetaAdapterFactory.getProperty(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e66065386d6bL, 0x76e4e660653879a3L, "status"), null) ? "HIGH" : "LOW");
  }
  public static Object propertyMacro_GetPropertyValue_5586951442585380792(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e66065386d87L, 0x76e4e6606538799eL, "sensor")), MetaAdapterFactory.getProperty(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e6606536afe0L, 0x76e4e6606536afe3L, "pin"));
  }
  public static Object propertyMacro_GetPropertyValue_5586951442585383816(final PropertyMacroContext _context) {
    return (SPropertyOperations.getBoolean_def(_context.getNode(), MetaAdapterFactory.getProperty(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e66065386d87L, 0x76e4e6606538799cL, "status"), null) ? "HIGH" : "LOW");
  }
  public static Object propertyMacro_GetPropertyValue_5586951442585391540(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e66065386d87L, 0x76e4e660653879a0L, "target")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetPropertyValue_5586951442585394666(final PropertyMacroContext _context) {
    return "" + _context.getSessionObject("current_state_name");
  }
  public static Object propertyMacro_GetPropertyValue_5586951442585418050(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static SNode sourceNodeQuery_5586951442585411393(final SourceSubstituteMacroNodeContext _context) {
    _context.putSessionObject("current_state_name", SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")));
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e66065386d30L, 0x76e4e66065387979L, "transition"));
  }
  public static Iterable<SNode> sourceNodesQuery_8567225692854966596(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e6606536afe7L, 0x76e4e6606536afeaL, "bricks"));
  }
  public static Iterable<SNode> sourceNodesQuery_5586951442585498561(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e6606536afe7L, 0x76e4e660653879c9L, "state"));
  }
  public static Iterable<SNode> sourceNodesQuery_5586951442585409453(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e66065386d30L, 0x76e4e66065387977L, "actions"));
  }
}
