package ArduinoML.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {

  /*package*/ final ConceptDescriptor myConceptAction = new ConceptDescriptorBuilder("ArduinoML.structure.Action", MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e66065386d6bL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(8567225692854974883L, "status")).properties("status").referenceDescriptors(new ConceptDescriptorBuilder.Ref(8567225692854974885L, "actuator", MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e6606536afe5L), false)).references("actuator").create();
  /*package*/ final ConceptDescriptor myConceptActuator = new ConceptDescriptorBuilder("ArduinoML.structure.Actuator", MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e6606536afe5L)).super_("ArduinoML.structure.Brick").super_(MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e6606536afe0L)).parents("ArduinoML.structure.Brick").parentIds(MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e6606536afe0L)).create();
  /*package*/ final ConceptDescriptor myConceptApp = new ConceptDescriptorBuilder("ArduinoML.structure.App", MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e6606536afe7L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.execution.util.structure.IMainClass", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, 0x40c1a7cb987d20d5L), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).referenceDescriptors(new ConceptDescriptorBuilder.Ref(8567225692854974924L, "init_state", MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e66065386d30L), false)).references("init_state").childDescriptors(new ConceptDescriptorBuilder.Link(8567225692854857706L, "bricks", MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e6606536afe0L), false, true, false), new ConceptDescriptorBuilder.Link(8567225692854974921L, "state", MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e66065386d30L), false, true, false)).children(new String[]{"bricks", "state"}, new boolean[]{true, true}).create();
  /*package*/ final ConceptDescriptor myConceptBrick = new ConceptDescriptorBuilder("ArduinoML.structure.Brick", MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e6606536afe0L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(8567225692854857699L, "pin")).properties("pin").abstract_().create();
  /*package*/ final ConceptDescriptor myConceptSensor = new ConceptDescriptorBuilder("ArduinoML.structure.Sensor", MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e6606536afe6L)).super_("ArduinoML.structure.Brick").super_(MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e6606536afe0L)).parents("ArduinoML.structure.Brick").parentIds(MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e6606536afe0L)).create();
  /*package*/ final ConceptDescriptor myConceptState = new ConceptDescriptorBuilder("ArduinoML.structure.State", MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e66065386d30L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).childDescriptors(new ConceptDescriptorBuilder.Link(8567225692854974839L, "actions", MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e66065386d6bL), true, true, false), new ConceptDescriptorBuilder.Link(8567225692854974841L, "transition", MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e66065386d87L), false, false, false)).children(new String[]{"actions", "transition"}, new boolean[]{true, false}).create();
  /*package*/ final ConceptDescriptor myConceptTransition = new ConceptDescriptorBuilder("ArduinoML.structure.Transition", MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e66065386d87L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(8567225692854974876L, "status")).properties("status").referenceDescriptors(new ConceptDescriptorBuilder.Ref(8567225692854974878L, "sensor", MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e6606536afe6L), false), new ConceptDescriptorBuilder.Ref(8567225692854974880L, "target", MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e66065386d30L), false)).references("sensor", "target").create();

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAction, myConceptActuator, myConceptApp, myConceptBrick, myConceptSensor, myConceptState, myConceptTransition);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0l, conceptFqName)) {
      case 0:
        return myConceptAction;
      case 1:
        return myConceptActuator;
      case 2:
        return myConceptApp;
      case 3:
        return myConceptBrick;
      case 4:
        return myConceptSensor;
      case 5:
        return myConceptState;
      case 6:
        return myConceptTransition;
      default:
        return null;
    }
  }
  private static String[] stringSwitchCases_1htk8d_a0a0l = new String[]{"ArduinoML.structure.Action", "ArduinoML.structure.Actuator", "ArduinoML.structure.App", "ArduinoML.structure.Brick", "ArduinoML.structure.Sensor", "ArduinoML.structure.State", "ArduinoML.structure.Transition"};
}
